### ISSUE TITLE
Spring 106.0+ TODO / Bugs in spring-106 branch

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#185]
### Ugly access
- [x] Port last functional gadget 'Control Victory'.
- [ ] Check all widgets, port essential/low hanging ones, hide expesive ones.
- [x] Polish for beta, make sure it works in a fresh environment.
- [x] Setup autohost with newest engine / game.
- [x] allow download via rapid (needs branch support / dedicated repo)

### QoL
- [ ] Rewrite monster widgets with some kind of plugin architecture. Worst offenders:
    - [ ] AdvPlayersListApm: 2.7 kloc
    - [ ] Top Bar: 1.8 kloc
    - [ ] Options: 1.4 kloc. I don't like this one, it toggles other widgets. Needs at least an option to stop doing that.
    - [ ] Build menu alternate: 1.4 kloc.
- [ ] Port remaining functional widgets.

### Eye candy
- [ ] Port gadget 'CustomUnitShaders'.
- [ ] Port or replace lups.
- [ ] Port or remove remaining eye candy widgets.

**Comment by CommanderSpice** [comment]
### Widget status
Autogenerated widget progress. 

**OPENGL**: Widget contains OpenGL 3 calls.
**FONT**: Widget contains old font calls: gl.(Begin|End)?Text.

Widgets not marked with OPENGL will probably just work.
A checkmark means the widget is tested and working.

- [X] Widget Selector:./widget_selector.lua:
- [ ] Adaptive graphics:./gfx_adaptive_graphics.lua:
- [ ] AdvPlayersList Game Info:./gui_advplayerslist_gameinfo.lua:OPENGL
- [ ] AdvPlayersList mascotte:./gui_advplayerslist_mascotte.lua:OPENGL
- [ ] AdvPlayersListApm:./gui_advplayerslist.lua:OPENGL FONT
- [ ] Ally Resource Bars (old):./gui_ally_res.lua:OPENGL FONT
- [ ] Ally Selected Units :./gui_allySelectedUnits.lua:OPENGL FONT
- [ ] AllyCursorsAll:./gui_ally_cursors_all.lua:OPENGL FONT
- [ ] Alternate Chat Keys:./cmd_old_style_chat_keys.lua:
- [ ] Anti Ranges:./gui_anti_ranges.lua:OPENGL
- [ ] Area Mex:./cmd_area_mex.lua:
- [ ] Area unload:./cmd_area_unload.lua:
- [ ] Armageddon Countdown:./gui_armageddon_countdown.lua:FONT
- [ ] Attack AoE:./gui_attack_aoe.lua:OPENGL
- [ ] Attack and Move Notification:./unit_attackMoveNotification.lua:
- [ ] Attack no ally:./cmd_attack_no_ally.lua:
- [ ] Auto First Build Facing:./unit_autofirstbuildfacing.lua:
- [ ] Auto Group:./unit_auto_group.lua:OPENGL
- [ ] Autoquit:./cmd_autoquit.lua:
- [ ] BA Hotkeys - swap YZ:./cmd_BA_hotkeys_swap_YZ.lua:
- [ ] BA Hotkeys Old:./cmd_BA_hotkeys_old.lua:
- [ ] BA Hotkeys:./cmd_BA_hotkeys.lua:
- [ ] BA LOS colors:./gui_ba_los_colors.lua:
- [ ] BA cmdcolors:./gfx_mod_cmdcolors.lua:
- [ ] Bind cloak to k:./bind_cloak.lua:
- [ ] Bomber control:./unit_bomber_control.lua:
- [ ] Build Split:./cmd_buildsplit.lua:
- [ ] Build menu alternate:./gui_buildmenu_alternate.lua:OPENGL
- [ ] BuildBar:./gui_buildbar.lua:OPENGL FONT
- [ ] BuildETA:./gui_build_eta.lua:FONT
- [ ] Camera groups:./camera_groups.lua:
- [ ] CameraFlip:./camera_flip.lua:
- [ ] CameraShake:./camera_shake.lua:
- [ ] Changelog Info:./gui_changelog_info.lua:OPENGL FONT
- [ ] Clearmapmarks button:./gui_clearmapmarks.lua:OPENGL
- [ ] Com DontBreakCloak:./unit_com_dontbreakcloak.lua:
- [ ] Comblast & Dgun Range old:./gui_comblast_dgun_range_old.lua:OPENGL FONT
- [ ] Comblast & Dgun Range:./gui_comblast_dgun_range.lua:OPENGL
- [ ] CommandInsert:./cmd_commandinsert.lua:
- [ ] Commander Hurt Vignette:./gui_commanderhurt.lua:OPENGL
- [ ] Commander Name Tags:./gui_com_nametags.lua:OPENGL
- [ ] Commands FX:./gui_commands_fx.lua:OPENGL
- [ ] Context Build:./cmd_context_build.lua:
- [ ] Contrast Adaptive Sharpen:./gfx_cas.lua:OPENGL
- [ ] Cursors3:./gfx_cursors.lua:
- [ ] CustomFormations2:./cmd_customformations2.lua:OPENGL
- [ ] DGun Stall Assist:./unit_dgun_stall_assist.lua:
- [ ] DGun no ground enemies:./cmd_dgun_no_ground_enemies.lua:
- [ ] Darken map:./gfx_darken_map.lua:OPENGL
- [ ] Default Group Recall Fix:./gui_group_recall_fix.lua:
- [ ] Defense Range old:./gui_defenserange_old.lua:OPENGL FONT
- [ ] Defense Range:./gui_defenserange.lua:OPENGL FONT
- [ ] Deferred rendering:./gfx_deferred_rendering.lua:OPENGL
- [ ] Disable Bad Widgets:./bad_widget_disabler.lua:
- [ ] Display DPS:./gui_display_dps.lua:FONT
- [ ] DontMove:./unit_dontmove.lua:
- [ ] EMP + decloak range:./gui_emp_decloak_range.lua:OPENGL
- [ ] Easy Facing:./gui_easyFacing.lua:OPENGL FONT
- [ ] Ecostats:./gui_ecostats.lua:OPENGL FONT
- [ ] EnemySpotter:./gui_enemy_spotter.lua:OPENGL
- [ ] Faction Change:./gui_faction_change.lua:OPENGL FONT
- [ ] Factory Auto-Repeat:./cmd_factory_repeat.lua:
- [ ] Factory hold position:./cmd_fac_holdposition.lua:
- [ ] FactoryGuard:./unit_factory_guard.lua:
- [ ] FactoryGuard_if_passive:./unit_factory_guard_passive.lua:
- [ ] FactoryQ Manager:./cmd_factoryqmanager.lua:FONT
- [ ] Fancy Selected Unit:./gui_fancy_selected_units.lua:OPENGL
- [ ] FlowUI:./gui_flowui.lua:OPENGL
- [ ] Frame Grapher:./dbg_frame_grapher.lua:FONT
- [ ] Game info:./gui_gameinfo.lua:OPENGL FONT
- [ ] GameTypeInfo:./gui_game_type_info.lua:FONT
- [ ] Ghost Radar:./unit_ghostRadar.lua:
- [ ] Ghost Site:./unit_ghostsite.lua:
- [ ] Given Units:./gui_given_units.lua:
- [ ] Grabinput:./grabinput.lua:
- [ ] Group Label:./gui_group_label.lua:FONT
- [ ] Health Bars:./gui_healthbars.lua:OPENGL FONT
- [ ] Highlight Geos:./gui_highlight_geos.lua:OPENGL
- [ ] Highlight Unit:./gui_highlight_unit.lua:OPENGL
- [ ] Holdfire Fix:./cmd_holdfire_fix.lua:
- [ ] Idle Builders:./gui_idle_builders.lua:OPENGL FONT
- [ ] Ignore List API:./api_ignore.lua:
- [ ] ImmobileBuilder:./unit_immobile_builder.lua:
- [ ] Info alternate:./gui_info_alternate.lua:OPENGL
- [ ] Initial Queue:./unit_initial_queue.lua:OPENGL FONT
- [ ] Keybind/Mouse Info:./gui_keybind_info.lua:OPENGL FONT
- [ ] LOS View:./gfx_los_view.lua:
- [ ] Light Effects:./gfx_light_effects.lua:
- [ ] Load Own Moving:./unit_load_own_moving.lua:
- [ ] Loop Select:./unit_loop_select.lua:OPENGL
- [ ] LupsManager:./gfx_lups_manager.lua:
- [ ] Map Draw Blocker:./map_draw_blocker.lua:
- [ ] Map Edge Extension Colourful:./map_edge_extension.lua:OPENGL
- [ ] Map External VR Grid:./map_external_grid.lua:OPENGL FONT
- [ ] Map Info:./gui_mapinfo.lua:OPENGL FONT
- [ ] Mapmarks FX:./gui_mapmarks_fx.lua:OPENGL FONT
- [X] Metalspot Finder:./api_metalspot_finder.lua:
- [X] Mex Snap:./cmd_mex_snap.lua:
- [ ] MexUpg Helper:./cmd_mex_upgrade_helper.lua:
- [ ] Mexclick Pro:./mexclick_pro.lua:OPENGL
- [ ] Mouse Buildspacing:./gui_buildspacing.lua:
- [ ] Mouse FX:./gui_mouse_fx.lua:OPENGL
- [ ] NoDuplicateOrders:./cmd_no_duplicate_orders.lua:
- [ ] OnlyFightersPatrol:./unit_only_fighters_patrol.lua:
- [ ] Options:./gui_options.lua:OPENGL FONT
- [ ] Order menu alternate:./ordermenu_alternate.lua:OPENGL
- [ ] Passive Everything:./passive_everything.lua:
- [ ] Passive builders v5:./unit_passive_builders.lua:OPENGL FONT
- [ ] Pause Screen:./gui_pausescreen.lua:OPENGL
- [ ] Persistent Build Spacing:./cmd_persistent_build_spacing.lua:
- [ ] Point Tracker:./gui_point_tracker.lua:OPENGL FONT
- [ ] Prospector:./gui_prospector.lua:OPENGL FONT
- [ ] Rank Icons:./gui_rank_icons.lua:
- [ ] ReclaimInfo:./gui_reclaiminfo.lua:FONT
- [ ] Red Console:./gui_red_console.lua:
- [ ] Red Minimap:./gui_red_minimap.lua:
- [ ] Red_Drawing:./red_ui_framework_drawing.lua:OPENGL FONT
- [ ] Red_UI_Framework:./red_ui_framework.lua:
- [ ] RelativeMinimap:./minimap_relative.lua:
- [ ] Select n Center!:./gui_center_n_select.lua:
- [ ] SelectAllUnitsOfSameTypeVisible:./unit_select_all_of_same_type_visible.lua:
- [ ] Selected Units Buttons:./gui_selbuttons.lua:OPENGL FONT
- [ ] Self-Destruct icons:./gui_selfd_icons.lua:
- [ ] Set target default:./cmd_default_set_target.lua:
- [ ] Share Tracker:./unit_share_tracker.lua:OPENGL FONT
- [ ] Show Orders:./gui_show_orders.lua:FONT
- [ ] Smart Area Reclaim:./unit_smart_area_reclaim.lua:
- [ ] SmartSelect:./unit_smart_select.lua:
- [ ] Smartguard Pro:./smartguard_pro.lua:
- [ ] Smarthotkeys pro:./smarthotkeys_pro.lua:
- [ ] SmoothCam:./camera_smoothcam.lua:
- [ ] Snow:./gfx_snow.lua:OPENGL
- [ ] Specific Unit Reclaimer:./unit_specific_unit_reclaimer.lua:
- [ ] Spectate Selected:./gui_spectate_selected.lua:
- [ ] Spy move/reclaim defaults:./unit_default_spy_move_cloaked.lua:
- [X] Start Boxes:./map_startbox.lua:
- [ ] State Remover:./cmd_state_remove.lua:
- [ ] State Reverse Toggle:./cmd_state_reverse_toggle.lua:
- [ ] Statistics Collection:./stats_damage.lua:
- [ ] Stockpiler (dynamic):./unit_stockpile_dynamic.lua:
- [ ] Stop means Stop:./cmd_stop_selfd.lua:
- [ ] Take Proxy:./cmd_take_proxy.lua:
- [ ] TeamPlatter:./gui_team_platter.lua:OPENGL
- [ ] TeamStats:./gui_teamstats.lua:OPENGL FONT
- [ ] Tooltip:./gui_tooltip.lua:OPENGL FONT
- [ ] Top Bar:./gui_top_bar.lua:OPENGL
- [ ] Transport AI:./unit_transport_ai.lua:
- [ ] Unit Finished Sounds:./snd_unit_finished.lua:
- [ ] Unit Info:./gui_unit_info.lua:OPENGL FONT
- [ ] Unit Marker:./gui_unit_marker.lua:
- [ ] Unit Mover:./cmd_unit_mover.lua:
- [ ] Unit Stats:./gui_unit_stats.lua:FONT
- [ ] Volume OSD:./snd_volume_osd.lua:
- [ ] Waypoint Dragger:./unit_waypoint_dragger_2.lua:OPENGL
- [ ] Widget Profiler:./dbg_widgetprofiler.lua:
- [ ] airlab_auto_fly:./airlab_auto_fly.lua:
- [ ] anon_ffa:./anon_ffa.lua:
- [ ] auto_reclaim_heal_assist:./auto_reclaim_heal_assist.lua:
- [ ] crawling bomb holdfire:./unit_crawling_bomb_holdfire.lua:
- [ ] fix colors:./cmd_fix_colors.lua:
- [ ] gui_transport_weight_limit:./gui_transport_weight_limit.lua:OPENGL
- [ ] replay buttons:./gui_replaybuttons.lua:OPENGL FONT
- [ ] set springsettings defaults:./set_springsettings_defaults.lua:
- [ ] shuffle colors:./cmd_shuffle_colors.lua:
- [ ] toggle los button:./gui_toggle_los.lua:OPENGL
- [ ] unit_cloak_sneaky_pete:./unit_cloak_sneakypete.lua:

**Comment by CommanderSpice** [comment]
A mirror with the branch spring-106 as master is [here](https://github.com/Balanced-Annihilation/Balanced-Annihilation-106). I will set up automatic updates, so we can continue using the branch spring-106 for development.

Because the mirror also contains ba tags, we need to pay attention to tag names. I propose starting at v16.0.0 for ba106 and keeping ba at v15.x.x to distinguish the branches.

ba106:test sounds good.

**Comment by FabriceFABS** [comment]
Yop,
Sure no problem.
Sorry it's been a long time I didn't play / managed.
«./pr-downloader ba106:test» is not found, what is the exact repo on rapid ?

Thanks !

**Comment by FabriceFABS** [comment]
OK Thank you, downloaded. Do you know the name of the MOD ?
Usually «Balanced\ Annihilation\ V15\.\d+\.\d+».
I tried V16\.\d+\.\d+, V16.0.0 and some others expression but I didn't find it actually...

**Comment by FabriceFABS** [comment]
OK I've found and works with «~Balanced\ Annihilation-106\ test-6218-16810fd»
Tools on bottom left are reversed ;)
https://i46.servimg.com/u/f46/19/33/95/58/spring10.png

However I should found the regular expression for auto-update feature...
I'm not so good with that, can you find it for me ?

**Comment by FabriceFABS** [comment]
For your information, PR-Downloader update is done eveyday @4:25 (AM) PARIS-Time and when Spads detects new MOD, it will restart and reload automatically.

I could set this more often if needed or another time.
Just let me know.

**Comment by CommanderSpice** [comment]
Can you also let it track the branch 'develop' of spring?
It currently uses spring-106.0.
Thanks!

**Comment by CommanderSpice** [comment]
How did you select that commit? It is kind of old and not the tip of any branch.

From the SPADS [doc](http://planetspads.free.fr/spads/doc/spadsDoc_All.html#global:autoManagedSpringVersion):
`autoManagedSpringVersion:unstable;60;whenOnlySpec`

This should check every hour for a new release and restart the host for an update when there are no players.

Can you also reduce the interval for a game update to 1 hour? That way the host won't be broken for a day if I mess up.

**Comment by FabriceFABS** [comment]
Hello !
Well I found right there, maybe it's not the right place : https://springrts.com/dl/buildbot/default/develop but I've just notice that I didn't go on the bottom of the list for the newest dev and picked the second from the top.

Thank you for the info, it's effective actually, every hour, Spads looks for new engine and update if no specs.
Well, your request also done for BA-Test update : Updated each time the clocks dispays «0» minute.
Also FYI too, I've just run the pr-download of BA-Test MOD in case of.
